# Generated by Django 5.2 on 2025-05-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='clas',
            new_name='class_name',
        ),
    ]
