# Generated by Django 5.2 on 2025-05-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doc_name',
            field=models.CharField(default='study material', max_length=100),
        ),
    ]
