# Generated by Django 5.2 on 2025-05-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ptofile',
            new_name='profile',
        ),
    ]
