# Generated by Django 5.2 on 2025-05-08 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
