# Generated by Django 5.2 on 2025-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subject_alter_class_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
