# Generated by Django 5.2 on 2025-05-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subject_alter_class_subject'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createschedule',
            name='hour1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hour1_schedules', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='createschedule',
            name='hour2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hour2_schedules', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='createschedule',
            name='hour3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hour3_schedules', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='createschedule',
            name='hour4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hour4_schedules', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='createschedule',
            name='hour5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hour5_schedules', to='accounts.subject'),
        ),
    ]
